name = "Nauty"
uuid = "d13d708c-e6ca-4145-9b59-cdd1b3737971"
authors = ["Laurent Bartholdi <laurent.bartholdi@gmail.com>"]
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
